# Generated by Django 6.0.5 on 2026-05-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_ai_confidence_product_ai_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='farmer',
        ),
        migrations.AddField(
            model_name='product',
            name='farmer_wallet',
            field=models.CharField(db_index=True, default='', max_length=120),
        ),
    ]
