[features]
seeds = false
skip-lint = false

[programs.devnet]
agrichain_proof_program = "Fg6PaFpoGXkYsidMpWxTWqkZQ6v8hF7s1M4fP7fJ8k7m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
